title: LexScope Agent
description: Civil and commercial law case analysis and regulation retrieval Agent platform.
theme: jekyll-theme-cayman
show_downloads: true
github:
  repository_url: https://github.com/ZephyrWn/lexscope-agent
